### ISSUE TITLE
New Logo For Mobell

### ISSUE THREAD

**Issue by zularizal** [kvaster/mobell#1]
Hi, I am a graphic designer, I want to help others in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. What do you think?

**Comment by kvaster** [comment]
Hi. It would be wonderfull to have logo!

пн, 14 мая 2018 г., 7:04 Zularizal <notifications@github.com>:

**Comment by zularizal** [comment]
Hi @kvaster , Is this project similar to a video player or cctv? Can you give more details about your project?

**Comment by kvaster** [comment]
This project is 'intercom'. It will work with mobotix cameras - mobotix door stations T25/T26. You will be able to receive incoming call from mobotix door station, to view your visitor. You will have bi-directional audio and you will be able to open door.

**Comment by zularizal** [comment]
I think it's a great app, I'll make a logo.

**Comment by zularizal** [comment]
Hi @kvaster , after I learned about the Mobotix T24 / T25, I think this app is related to the camera, so I made a logo with camera and door. And this is the result of design. What do you think?
If there's something you want to change, let me know

![logo](https://user-images.githubusercontent.com/38547278/40263691-65081aa2-5b40-11e8-88a5-0bff1c1ebf3d.png)

**Comment by kvaster** [comment]
Looks good!

**Comment by zularizal** [comment]
Okay, i will close this issue
