### ISSUE TITLE
No working in background 

### ISSUE THREAD

**Issue by melkati** [kvaster/mobell#3]
Old version 1.0 worked fine while in background. 
Last version in Store won’t come on when somebody rings the bell. 
I was searching for the old Apk but can’t find it at any “safe” repository 

I’m running it on a Xiaomi A1 with Android 9

**Comment by kvaster** [comment]
Telling the truth, nothing was change in 'background' code from 1.0 to 1.1 version... It must be some setting on your phone...

**Comment by kvaster** [comment]
I have a new hardware now (android tablets) and finally I've managed to test all.

v1.3 comes with lot's of bugs fixed. Now connection is properly handled - you need to turn on 'Disable battery optimization' in options.
