### ISSUE TITLE
EventStreamClient Android SDK now also available

### ISSUE THREAD

**Issue by JumboF** [kvaster/mobell#4]
Hello kvaster,

Thanks for the MoBell SW - I use it successfully on an Android IP phone to interact with my Mobotix T25. Everything works correctly so far. But I would still like to have the app activated automatically by an event (doorbell).

I noticed that Mobotix also offers an Android EventStream SDK since Jan. 2019 (V1.1.0).
Would this have made your efforts to reverse engineer the MxPEG format easier or possibly given you new ways to react to events (MxMessages) in case of a doorbell?

I am not an experienced programmer - so I apologize if I have not expressed myself correctly.
Any help/suggestion would be appreciated.

Greetings, 
JumboF

**Comment by kvaster** [comment]
App 'IS' automatically activated on my phone (Samsung S10+) and on my tables (old Huawei Media Pad M3). Also I've tested on some other devices.

The main purpose of this app is to interact with T25 without internet access. Generally I developed it for my android tables which I'm using as control panels for my home devices.

Make sure you have enaled 'Run in background' and 'Keep wifi fast'. This settings will drain battery a bit more. After that background service will connect to T25 and will ping it every 2 minutes keeping connection alive.

Also you should check your settings on T25 in 'Bell Behavior and Video Mailbox'. Make sure you can see Mobell in 'Set Remote Stations for Door Station'. And also in 'Set Remote Stations for Door Station' (you should click 'more' to see this options).

In case it doesn't help -> is it all ok with door bell when mobell is in foreground ?

**Comment by kvaster** [comment]
I've managed to fix all problems with doorbell on latest android versions. It's fixed in v1.3. Probably will need to wait some time until it will be available in PlayStore.
